// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Popover',
  tags: ['autodocs'],
  argTypes: {
    dismissible: { control: 'boolean', description: 'Whether the popover closes on outside click or Escape.' },
    open: { control: 'boolean', description: 'Whether the popover is currently visible.' },
    placement: {
      control: 'select',
      options: ['bottom', 'bottom-end', 'bottom-start', 'left', 'right', 'top', 'top-end', 'top-start'],
      description: 'Placement of the popover relative to the trigger.'
    },
    trigger: {
      control: 'select',
      options: ['click', 'hover', 'manual'],
      description: 'How the popover is triggered.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.dismissible) attrs.push('dismissible');
  if (args.open) attrs.push('open');
  if (args.placement !== undefined && args.placement !== null) attrs.push(`placement="${args.placement}"`);
  if (args.trigger !== undefined && args.trigger !== null) attrs.push(`trigger="${args.trigger}"`);
  return `<ts-popover ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="trigger">${args['slot_trigger'] || ''}</span>
  </ts-popover>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "dismissible": true,
      "open": false,
      "placement": "bottom",
      "trigger": "click",
      "slotContent": "Content"
  },
});

