// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Step',
  tags: ['autodocs'],
  argTypes: {
    completed: { control: 'boolean', description: 'Whether this step is completed.' },
    description: { control: 'text', description: 'Optional description text below the label.' },
    disabled: { control: 'boolean', description: 'Whether this step is disabled.' },
    error: { control: 'boolean', description: 'Whether this step has an error.' },
    icon: { control: 'text', description: 'Optional custom icon name.' },
    label: { control: 'text', description: 'The step label text.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.completed) attrs.push('completed');
  if (args.description !== undefined && args.description !== null) attrs.push(`description="${args.description}"`);
  if (args.disabled) attrs.push('disabled');
  if (args.error) attrs.push('error');
  if (args.icon !== undefined && args.icon !== null) attrs.push(`icon="${args.icon}"`);
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  return `<ts-step ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-step>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "completed": false,
      "disabled": false,
      "error": false,
      "slotContent": "Content"
  },
});

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-step>Default</ts-step>
    <ts-step disabled>Disabled</ts-step>
  </div>
`;

