// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Stepper',
  tags: ['autodocs'],
  argTypes: {
    activeStep: { control: 'number', description: 'The index of the currently active step (0-based).' },
    linear: { control: 'boolean', description: 'If true, steps must be completed in order.' },
    orientation: {
      control: 'select',
      options: ['horizontal', 'vertical'],
      description: 'The layout orientation.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.activeStep !== undefined && args.activeStep !== null) attrs.push(`active-step="${args.activeStep}"`);
  if (args.linear) attrs.push('linear');
  if (args.orientation !== undefined && args.orientation !== null) attrs.push(`orientation="${args.orientation}"`);
  return `<ts-stepper ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-stepper>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "activeStep": 0,
      "linear": false,
      "orientation": "horizontal",
      "slotContent": "Content"
  },
});

