// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Pagination',
  tags: ['autodocs'],
  argTypes: {
    currentPage: { control: 'number', description: 'The current active page (1-based).' },
    pageSize: { control: 'number', description: 'Number of items per page.' },
    siblingCount: { control: 'number', description: 'Number of sibling pages shown around the current page.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The size of the pagination buttons.'
    },
    total: { control: 'number', description: 'Total number of items.' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.currentPage !== undefined && args.currentPage !== null) attrs.push(`current-page="${args.currentPage}"`);
  if (args.pageSize !== undefined && args.pageSize !== null) attrs.push(`page-size="${args.pageSize}"`);
  if (args.siblingCount !== undefined && args.siblingCount !== null) attrs.push(`sibling-count="${args.siblingCount}"`);
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.total !== undefined && args.total !== null) attrs.push(`total="${args.total}"`);
  return `<ts-pagination ${attrs.join(' ')}>
  </ts-pagination>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "currentPage": 1,
      "pageSize": 10,
      "siblingCount": 1,
      "size": "md"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-pagination size="lg"></ts-pagination>
    <ts-pagination size="md"></ts-pagination>
    <ts-pagination size="sm"></ts-pagination>
    <ts-pagination size="xl"></ts-pagination>
    <ts-pagination size="xs"></ts-pagination>
  </div>
`;

