// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Radio',
  tags: ['autodocs'],
  argTypes: {
    checked: { control: 'boolean', description: 'Whether the radio is checked.' },
    disabled: { control: 'boolean', description: 'Renders the radio as disabled.' },
    label: { control: 'text', description: 'Label text. If omitted, use the default slot.' },
    name: { control: 'text', description: 'Name attribute for form submission.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm'],
      description: 'The radio size.'
    },
    value: { control: 'text', description: 'The value associated with this radio.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.checked) attrs.push('checked');
  if (args.disabled) attrs.push('disabled');
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.name !== undefined && args.name !== null) attrs.push(`name="${args.name}"`);
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-radio ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-radio>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "checked": false,
      "disabled": false,
      "size": "md",
      "value": "",
      "slotContent": "Content"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-radio size="lg">LG</ts-radio>
    <ts-radio size="md">MD</ts-radio>
    <ts-radio size="sm">SM</ts-radio>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-radio>Default</ts-radio>
    <ts-radio checked>Checked</ts-radio>
    <ts-radio disabled>Disabled</ts-radio>
  </div>
`;

