// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Input',
  tags: ['autodocs'],
  argTypes: {
    autocomplete: { control: 'text', description: 'Autocomplete attribute.' },
    disabled: { control: 'boolean', description: 'Renders the input as disabled.' },
    error: { control: 'text', description: 'Renders the input in an error state with an error message.' },
    helpText: { control: 'text', description: 'Help text displayed below the input.' },
    label: { control: 'text', description: 'Label text displayed above the input.' },
    maxlength: { control: 'text', description: 'Maximum character length.' },
    minlength: { control: 'text', description: 'Minimum character length.' },
    name: { control: 'text', description: 'Name attribute for form submission.' },
    pattern: { control: 'text', description: 'Pattern for validation (regex string).' },
    placeholder: { control: 'text', description: 'Placeholder text.' },
    readonly: { control: 'boolean', description: 'Renders the input as readonly.' },
    required: { control: 'boolean', description: 'Makes the input required.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The input\'s size.'
    },
    type: {
      control: 'select',
      options: ['email', 'number', 'password', 'search', 'tel', 'text', 'url'],
      description: 'The input type.'
    },
    value: { control: 'text', description: 'The input\'s value.' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.autocomplete !== undefined && args.autocomplete !== null) attrs.push(`autocomplete="${args.autocomplete}"`);
  if (args.disabled) attrs.push('disabled');
  if (args.error !== undefined && args.error !== null) attrs.push(`error="${args.error}"`);
  if (args.helpText !== undefined && args.helpText !== null) attrs.push(`help-text="${args.helpText}"`);
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.maxlength !== undefined && args.maxlength !== null) attrs.push(`maxlength="${args.maxlength}"`);
  if (args.minlength !== undefined && args.minlength !== null) attrs.push(`minlength="${args.minlength}"`);
  if (args.name !== undefined && args.name !== null) attrs.push(`name="${args.name}"`);
  if (args.pattern !== undefined && args.pattern !== null) attrs.push(`pattern="${args.pattern}"`);
  if (args.placeholder !== undefined && args.placeholder !== null) attrs.push(`placeholder="${args.placeholder}"`);
  if (args.readonly) attrs.push('readonly');
  if (args.required) attrs.push('required');
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.type !== undefined && args.type !== null) attrs.push(`type="${args.type}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-input ${attrs.join(' ')}>
    <span slot="help-text">${args['slot_help-text'] || ''}</span>
    <span slot="prefix">${args['slot_prefix'] || ''}</span>
    <span slot="suffix">${args['slot_suffix'] || ''}</span>
  </ts-input>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "readonly": false,
      "required": false,
      "size": "md",
      "type": "text",
      "value": ""
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-input size="lg"></ts-input>
    <ts-input size="md"></ts-input>
    <ts-input size="sm"></ts-input>
    <ts-input size="xl"></ts-input>
    <ts-input size="xs"></ts-input>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-input></ts-input>
    <ts-input disabled></ts-input>
    <ts-input readonly></ts-input>
  </div>
`;

