// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Badge',
  tags: ['autodocs'],
  argTypes: {
    dot: { control: 'boolean', description: 'Renders the badge as a small dot indicator (content is hidden).' },
    outline: { control: 'boolean', description: 'Renders an outlined style instead of solid.' },
    pill: { control: 'boolean', description: 'Renders the badge with rounded-pill shape.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The badge\'s size.'
    },
    variant: {
      control: 'select',
      options: ['danger', 'info', 'neutral', 'primary', 'secondary', 'success', 'warning'],
      description: 'The badge\'s color variant.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.dot) attrs.push('dot');
  if (args.outline) attrs.push('outline');
  if (args.pill) attrs.push('pill');
  if (args.size != null) attrs.push(`size="${args.size}"`);
  if (args.variant != null) attrs.push(`variant="${args.variant}"`);
  return `<ts-badge ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-badge>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "dot": false,
      "outline": false,
      "pill": false,
      "size": "md",
      "variant": "primary",
      "slotContent": "Content"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-badge variant="danger">Danger</ts-badge>
    <ts-badge variant="info">Info</ts-badge>
    <ts-badge variant="neutral">Neutral</ts-badge>
    <ts-badge variant="primary">Primary</ts-badge>
    <ts-badge variant="secondary">Secondary</ts-badge>
    <ts-badge variant="success">Success</ts-badge>
    <ts-badge variant="warning">Warning</ts-badge>
  </div>
`;

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-badge size="lg">LG</ts-badge>
    <ts-badge size="md">MD</ts-badge>
    <ts-badge size="sm">SM</ts-badge>
    <ts-badge size="xl">XL</ts-badge>
    <ts-badge size="xs">XS</ts-badge>
  </div>
`;

