// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Button',
  tags: ['autodocs'],
  argTypes: {
    appearance: {
      control: 'select',
      options: ['ghost', 'link', 'outline', 'solid'],
      description: 'The button\'s visual weight / appearance.'
    },
    block: { control: 'boolean', description: 'Makes the button take the full width of its container.' },
    disabled: { control: 'boolean', description: 'Renders the button in a disabled state.' },
    href: { control: 'text', description: 'An optional href — renders an anchor instead of a button.' },
    loading: { control: 'boolean', description: 'Renders a loading spinner and disables the button.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The button\'s size.'
    },
    target: {
      control: 'select',
      options: ['_blank', '_parent', '_self', '_top'],
      description: 'Target attribute when href is set.'
    },
    type: {
      control: 'select',
      options: ['button', 'reset', 'submit'],
      description: 'The type attribute for the native button.'
    },
    variant: {
      control: 'select',
      options: ['danger', 'info', 'neutral', 'primary', 'secondary', 'success', 'warning'],
      description: 'The button\'s visual variant.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.appearance != null) attrs.push(`appearance="${args.appearance}"`);
  if (args.block) attrs.push('block');
  if (args.disabled) attrs.push('disabled');
  if (args.href != null) attrs.push(`href="${args.href}"`);
  if (args.loading) attrs.push('loading');
  if (args.size != null) attrs.push(`size="${args.size}"`);
  if (args.target != null) attrs.push(`target="${args.target}"`);
  if (args.type != null) attrs.push(`type="${args.type}"`);
  if (args.variant != null) attrs.push(`variant="${args.variant}"`);
  return `<ts-button ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="prefix">${args['slot_prefix'] || ''}</span>
    <span slot="suffix">${args['slot_suffix'] || ''}</span>
  </ts-button>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "appearance": "solid",
      "block": false,
      "disabled": false,
      "loading": false,
      "size": "md",
      "type": "button",
      "variant": "primary",
      "slotContent": "Content"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-button variant="danger">Danger</ts-button>
    <ts-button variant="info">Info</ts-button>
    <ts-button variant="neutral">Neutral</ts-button>
    <ts-button variant="primary">Primary</ts-button>
    <ts-button variant="secondary">Secondary</ts-button>
    <ts-button variant="success">Success</ts-button>
    <ts-button variant="warning">Warning</ts-button>
  </div>
`;

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-button size="lg">LG</ts-button>
    <ts-button size="md">MD</ts-button>
    <ts-button size="sm">SM</ts-button>
    <ts-button size="xl">XL</ts-button>
    <ts-button size="xs">XS</ts-button>
  </div>
`;

export const Appearances = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-button appearance="ghost">Ghost</ts-button>
    <ts-button appearance="link">Link</ts-button>
    <ts-button appearance="outline">Outline</ts-button>
    <ts-button appearance="solid">Solid</ts-button>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-button>Default</ts-button>
    <ts-button disabled>Disabled</ts-button>
    <ts-button loading>Loading</ts-button>
  </div>
`;

