// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/MenuItem',
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean', description: 'Disables the menu item.' },
    href: { control: 'text', description: 'If provided, renders the item as a link.' },
    value: { control: 'text', description: 'The value associated with this menu item.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.disabled) attrs.push('disabled');
  if (args.href !== undefined && args.href !== null) attrs.push(`href="${args.href}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-menu-item ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="prefix">${args['slot_prefix'] || ''}</span>
    <span slot="suffix">${args['slot_suffix'] || ''}</span>
  </ts-menu-item>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "value": "",
      "slotContent": "Content"
  },
});

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-menu-item>Default</ts-menu-item>
    <ts-menu-item disabled>Disabled</ts-menu-item>
  </div>
`;

