// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/MenuDivider',
  tags: ['autodocs'],
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  return `<ts-menu-divider ${attrs.join(' ')}>
  </ts-menu-divider>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {},
});

