// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Menu',
  tags: ['autodocs'],
  argTypes: {
    open: { control: 'boolean', description: 'Whether the menu dropdown is open.' },
    placement: {
      control: 'select',
      options: ['bottom-end', 'bottom-start', 'top-end', 'top-start'],
      description: 'Placement of the dropdown relative to the trigger.'
    },
    trigger: {
      control: 'select',
      options: ['click', 'hover'],
      description: 'How the menu is triggered.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.open) attrs.push('open');
  if (args.placement !== undefined && args.placement !== null) attrs.push(`placement="${args.placement}"`);
  if (args.trigger !== undefined && args.trigger !== null) attrs.push(`trigger="${args.trigger}"`);
  return `<ts-menu ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="trigger">${args['slot_trigger'] || ''}</span>
  </ts-menu>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "open": false,
      "placement": "bottom-start",
      "trigger": "click",
      "slotContent": "Content"
  },
});

