// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Textarea',
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean', description: 'Renders the textarea as disabled.' },
    error: { control: 'boolean', description: 'Renders the textarea in an error state.' },
    errorMessage: { control: 'text', description: 'Error message displayed below the textarea.' },
    helpText: { control: 'text', description: 'Help text displayed below the textarea.' },
    label: { control: 'text', description: 'Label text displayed above the textarea.' },
    maxlength: { control: 'text', description: 'Maximum character length.' },
    name: { control: 'text', description: 'Name attribute for form submission.' },
    placeholder: { control: 'text', description: 'Placeholder text.' },
    readonly: { control: 'boolean', description: 'Renders the textarea as readonly.' },
    required: { control: 'boolean', description: 'Makes the textarea required.' },
    resize: {
      control: 'select',
      options: ['both', 'horizontal', 'none', 'vertical'],
      description: 'Resize behavior.'
    },
    rows: { control: 'number', description: 'Number of visible text rows.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The textarea size.'
    },
    value: { control: 'text', description: 'The textarea\'s value.' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.disabled) attrs.push('disabled');
  if (args.error) attrs.push('error');
  if (args.errorMessage !== undefined && args.errorMessage !== null) attrs.push(`error-message="${args.errorMessage}"`);
  if (args.helpText !== undefined && args.helpText !== null) attrs.push(`help-text="${args.helpText}"`);
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.maxlength !== undefined && args.maxlength !== null) attrs.push(`maxlength="${args.maxlength}"`);
  if (args.name !== undefined && args.name !== null) attrs.push(`name="${args.name}"`);
  if (args.placeholder !== undefined && args.placeholder !== null) attrs.push(`placeholder="${args.placeholder}"`);
  if (args.readonly) attrs.push('readonly');
  if (args.required) attrs.push('required');
  if (args.resize !== undefined && args.resize !== null) attrs.push(`resize="${args.resize}"`);
  if (args.rows !== undefined && args.rows !== null) attrs.push(`rows="${args.rows}"`);
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-textarea ${attrs.join(' ')}>
  </ts-textarea>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "error": false,
      "readonly": false,
      "required": false,
      "resize": "vertical",
      "rows": 3,
      "size": "md",
      "value": ""
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-textarea size="lg"></ts-textarea>
    <ts-textarea size="md"></ts-textarea>
    <ts-textarea size="sm"></ts-textarea>
    <ts-textarea size="xl"></ts-textarea>
    <ts-textarea size="xs"></ts-textarea>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-textarea></ts-textarea>
    <ts-textarea disabled></ts-textarea>
    <ts-textarea readonly></ts-textarea>
  </div>
`;

