// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/TabPanel',
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean', description: 'Whether this tab is disabled.' },
    icon: { control: 'text', description: 'Optional icon name displayed before the tab label.' },
    tab: { control: 'text', description: 'The label text displayed in the tab button.' },
    value: { control: 'text', description: 'Unique identifier for this tab panel.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.disabled) attrs.push('disabled');
  if (args.icon !== undefined && args.icon !== null) attrs.push(`icon="${args.icon}"`);
  if (args.tab !== undefined && args.tab !== null) attrs.push(`tab="${args.tab}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-tab-panel ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-tab-panel>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "slotContent": "Content"
  },
});

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-tab-panel>Default</ts-tab-panel>
    <ts-tab-panel disabled>Disabled</ts-tab-panel>
  </div>
`;

