// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Tabs',
  tags: ['autodocs'],
  argTypes: {
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm'],
      description: 'The size of the tab buttons.'
    },
    value: { control: 'text', description: 'The value of the currently active tab.' },
    variant: {
      control: 'select',
      options: ['enclosed', 'line', 'pill'],
      description: 'Visual variant of the tab bar.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  return `<ts-tabs ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-tabs>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "size": "md",
      "variant": "line",
      "slotContent": "Content"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-tabs variant="enclosed">Enclosed</ts-tabs>
    <ts-tabs variant="line">Line</ts-tabs>
    <ts-tabs variant="pill">Pill</ts-tabs>
  </div>
`;

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-tabs size="lg">LG</ts-tabs>
    <ts-tabs size="md">MD</ts-tabs>
    <ts-tabs size="sm">SM</ts-tabs>
  </div>
`;

