// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Toast',
  tags: ['autodocs'],
  argTypes: {
    dismissible: { control: 'boolean', description: 'Whether the toast shows a close button.' },
    duration: { control: 'number', description: 'Auto-dismiss duration in ms. Set 0 to disable.' },
    open: { control: 'boolean', description: 'Whether the toast is visible.' },
    position: {
      control: 'select',
      options: ['bottom-center', 'bottom-left', 'bottom-right', 'top-center', 'top-left', 'top-right'],
      description: 'Position of the toast on screen.'
    },
    variant: {
      control: 'select',
      options: ['danger', 'info', 'neutral', 'success', 'warning'],
      description: 'The toast\'s visual variant.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.dismissible) attrs.push('dismissible');
  if (args.duration !== undefined && args.duration !== null) attrs.push(`duration="${args.duration}"`);
  if (args.open) attrs.push('open');
  if (args.position !== undefined && args.position !== null) attrs.push(`position="${args.position}"`);
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  return `<ts-toast ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="action">${args['slot_action'] || ''}</span>
  </ts-toast>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "dismissible": true,
      "duration": 5000,
      "open": false,
      "position": "top-right",
      "variant": "info",
      "slotContent": "Content"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-toast variant="danger">Danger</ts-toast>
    <ts-toast variant="info">Info</ts-toast>
    <ts-toast variant="neutral">Neutral</ts-toast>
    <ts-toast variant="success">Success</ts-toast>
    <ts-toast variant="warning">Warning</ts-toast>
  </div>
`;

