// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Toolbar',
  tags: ['autodocs'],
  argTypes: {
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The toolbar size.'
    },
    variant: {
      control: 'select',
      options: ['bordered', 'default', 'elevated'],
      description: 'The toolbar variant style.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  return `<ts-toolbar ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="end">${args['slot_end'] || ''}</span>
    <span slot="start">${args['slot_start'] || ''}</span>
  </ts-toolbar>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "size": "md",
      "variant": "default",
      "slotContent": "Content"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-toolbar variant="bordered">Bordered</ts-toolbar>
    <ts-toolbar variant="default">Default</ts-toolbar>
    <ts-toolbar variant="elevated">Elevated</ts-toolbar>
  </div>
`;

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-toolbar size="lg">LG</ts-toolbar>
    <ts-toolbar size="md">MD</ts-toolbar>
    <ts-toolbar size="sm">SM</ts-toolbar>
    <ts-toolbar size="xl">XL</ts-toolbar>
    <ts-toolbar size="xs">XS</ts-toolbar>
  </div>
`;

