// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Progress',
  tags: ['autodocs'],
  argTypes: {
    indeterminate: { control: 'boolean', description: 'Whether the progress is indeterminate.' },
    label: { control: 'text', description: 'Accessible label for the progress bar.' },
    max: { control: 'number', description: 'Maximum value.' },
    showValue: { control: 'boolean', description: 'Whether to display the percentage value.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The size of the progress bar.'
    },
    value: { control: 'number', description: 'Current progress value (0 to max).' },
    variant: {
      control: 'select',
      options: ['danger', 'info', 'primary', 'success', 'warning'],
      description: 'The color variant.'
    },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.indeterminate) attrs.push('indeterminate');
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.max !== undefined && args.max !== null) attrs.push(`max="${args.max}"`);
  if (args.showValue) attrs.push('show-value');
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  return `<ts-progress ${attrs.join(' ')}>
  </ts-progress>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "indeterminate": false,
      "max": 100,
      "showValue": false,
      "size": "md",
      "value": 0,
      "variant": "primary"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-progress variant="danger"></ts-progress>
    <ts-progress variant="info"></ts-progress>
    <ts-progress variant="primary"></ts-progress>
    <ts-progress variant="success"></ts-progress>
    <ts-progress variant="warning"></ts-progress>
  </div>
`;

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-progress size="lg"></ts-progress>
    <ts-progress size="md"></ts-progress>
    <ts-progress size="sm"></ts-progress>
    <ts-progress size="xl"></ts-progress>
    <ts-progress size="xs"></ts-progress>
  </div>
`;

