// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Spinner',
  tags: ['autodocs'],
  argTypes: {
    color: { control: 'text', description: 'The color of the spinning indicator.' },
    label: { control: 'text', description: 'Accessible label for screen readers.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The size of the spinner.'
    },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.color !== undefined && args.color !== null) attrs.push(`color="${args.color}"`);
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  return `<ts-spinner ${attrs.join(' ')}>
  </ts-spinner>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "color": "currentColor",
      "label": "Loading",
      "size": "md"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-spinner size="lg"></ts-spinner>
    <ts-spinner size="md"></ts-spinner>
    <ts-spinner size="sm"></ts-spinner>
    <ts-spinner size="xl"></ts-spinner>
    <ts-spinner size="xs"></ts-spinner>
  </div>
`;

