// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/BreadcrumbItem',
  tags: ['autodocs'],
  argTypes: {
    current: { control: 'boolean', description: 'Marks this item as the current page.' },
    href: { control: 'text', description: 'If set, renders as a link.' },
    separator: { control: 'text', description: 'Separator character (set by parent ts-breadcrumb).' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.current) attrs.push('current');
  if (args.href !== undefined && args.href !== null) attrs.push(`href="${args.href}"`);
  if (args.separator !== undefined && args.separator !== null) attrs.push(`separator="${args.separator}"`);
  return `<ts-breadcrumb-item ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-breadcrumb-item>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "current": false,
      "slotContent": "Content"
  },
});

