// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Breadcrumb',
  tags: ['autodocs'],
  argTypes: {
    separator: { control: 'text', description: 'The separator character between breadcrumb items.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.separator !== undefined && args.separator !== null) attrs.push(`separator="${args.separator}"`);
  return `<ts-breadcrumb ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-breadcrumb>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "separator": "/",
      "slotContent": "Content"
  },
});

