// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Select',
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean', description: 'Renders the select as disabled.' },
    error: { control: 'boolean', description: 'Renders the select in an error state.' },
    errorMessage: { control: 'text', description: 'Error message displayed below the select.' },
    helpText: { control: 'text', description: 'Help text displayed below the select.' },
    label: { control: 'text', description: 'Label text displayed above the select.' },
    multiple: { control: 'boolean', description: 'Allow multiple selections.' },
    name: { control: 'text', description: 'Name attribute for form submission.' },
    placeholder: { control: 'text', description: 'Placeholder text when no value is selected.' },
    required: { control: 'boolean', description: 'Makes the select required.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The select size.'
    },
    value: { control: 'text', description: 'The current value.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.disabled) attrs.push('disabled');
  if (args.error) attrs.push('error');
  if (args.errorMessage !== undefined && args.errorMessage !== null) attrs.push(`error-message="${args.errorMessage}"`);
  if (args.helpText !== undefined && args.helpText !== null) attrs.push(`help-text="${args.helpText}"`);
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.multiple) attrs.push('multiple');
  if (args.name !== undefined && args.name !== null) attrs.push(`name="${args.name}"`);
  if (args.placeholder !== undefined && args.placeholder !== null) attrs.push(`placeholder="${args.placeholder}"`);
  if (args.required) attrs.push('required');
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-select ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-select>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "error": false,
      "multiple": false,
      "required": false,
      "size": "md",
      "value": "",
      "slotContent": "Content"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-select size="lg">LG</ts-select>
    <ts-select size="md">MD</ts-select>
    <ts-select size="sm">SM</ts-select>
    <ts-select size="xl">XL</ts-select>
    <ts-select size="xs">XS</ts-select>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-select>Default</ts-select>
    <ts-select disabled>Disabled</ts-select>
  </div>
`;

