// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/FileUpload',
  tags: ['autodocs'],
  argTypes: {
    accept: { control: 'text', description: 'Accepted file types (e.g. \'.jpg,.png\').' },
    disabled: { control: 'boolean', description: 'Whether the file upload is disabled.' },
    label: { control: 'text', description: 'Label text for the dropzone.' },
    maxSize: { control: 'text', description: 'Maximum file size in bytes.' },
    multiple: { control: 'boolean', description: 'Whether multiple files can be selected.' },
    name: { control: 'text', description: 'Form field name.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.accept !== undefined && args.accept !== null) attrs.push(`accept="${args.accept}"`);
  if (args.disabled) attrs.push('disabled');
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.maxSize !== undefined && args.maxSize !== null) attrs.push(`max-size="${args.maxSize}"`);
  if (args.multiple) attrs.push('multiple');
  if (args.name !== undefined && args.name !== null) attrs.push(`name="${args.name}"`);
  return `<ts-file-upload ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-file-upload>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "label": "Drop files here or click to upload",
      "multiple": false,
      "slotContent": "Content"
  },
});

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-file-upload>Default</ts-file-upload>
    <ts-file-upload disabled>Disabled</ts-file-upload>
  </div>
`;

