// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Skeleton',
  tags: ['autodocs'],
  argTypes: {
    animation: {
      control: 'select',
      options: ['none', 'pulse', 'wave'],
      description: 'Animation style.'
    },
    height: { control: 'text', description: 'CSS height of the skeleton.' },
    lines: { control: 'number', description: 'Number of lines to render (text variant only).' },
    variant: {
      control: 'select',
      options: ['circular', 'rectangular', 'text'],
      description: 'The skeleton shape variant.'
    },
    width: { control: 'text', description: 'CSS width of the skeleton.' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.animation !== undefined && args.animation !== null) attrs.push(`animation="${args.animation}"`);
  if (args.height !== undefined && args.height !== null) attrs.push(`height="${args.height}"`);
  if (args.lines !== undefined && args.lines !== null) attrs.push(`lines="${args.lines}"`);
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  if (args.width !== undefined && args.width !== null) attrs.push(`width="${args.width}"`);
  return `<ts-skeleton ${attrs.join(' ')}>
  </ts-skeleton>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "animation": "pulse",
      "lines": 1,
      "variant": "text",
      "width": "100%"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-skeleton variant="circular"></ts-skeleton>
    <ts-skeleton variant="rectangular"></ts-skeleton>
    <ts-skeleton variant="text"></ts-skeleton>
  </div>
`;

