// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Card',
  tags: ['autodocs'],
  argTypes: {
    bordered: { control: 'boolean', description: 'Border style variant.' },
    elevation: {
      control: 'select',
      options: ['lg', 'md', 'none', 'sm', 'xl'],
      description: 'Elevation level controlling the shadow depth.'
    },
    interactive: { control: 'boolean', description: 'Makes the card interactive (hover effect, cursor pointer).' },
    padding: {
      control: 'select',
      options: ['lg', 'md', 'none', 'sm'],
      description: 'Padding size for the card body.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.bordered) attrs.push('bordered');
  if (args.elevation != null) attrs.push(`elevation="${args.elevation}"`);
  if (args.interactive) attrs.push('interactive');
  if (args.padding != null) attrs.push(`padding="${args.padding}"`);
  return `<ts-card ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="footer">${args['slot_footer'] || ''}</span>
    <span slot="header">${args['slot_header'] || ''}</span>
    <span slot="media">${args['slot_media'] || ''}</span>
  </ts-card>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "bordered": false,
      "elevation": "sm",
      "interactive": false,
      "padding": "md",
      "slotContent": "Content"
  },
});

