// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Icon',
  tags: ['autodocs'],
  argTypes: {
    color: { control: 'text', description: 'CSS color value applied to the icon.' },
    label: { control: 'text', description: 'Accessible label. When set, applies role="img" and aria-label. When absent, sets aria-hidden="true".' },
    name: { control: 'text', description: 'Icon name for future icon registry lookup.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The icon\'s size.'
    },
    src: { control: 'text', description: 'URL to an external SVG icon file.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.color !== undefined && args.color !== null) attrs.push(`color="${args.color}"`);
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.name !== undefined && args.name !== null) attrs.push(`name="${args.name}"`);
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.src !== undefined && args.src !== null) attrs.push(`src="${args.src}"`);
  return `<ts-icon ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-icon>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "color": "currentColor",
      "size": "md",
      "slotContent": "Content"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-icon size="lg">LG</ts-icon>
    <ts-icon size="md">MD</ts-icon>
    <ts-icon size="sm">SM</ts-icon>
    <ts-icon size="xl">XL</ts-icon>
    <ts-icon size="xs">XS</ts-icon>
  </div>
`;

