// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Divider',
  tags: ['autodocs'],
  argTypes: {
    label: { control: 'text', description: 'Optional label text displayed in the center of the divider.' },
    orientation: {
      control: 'select',
      options: ['horizontal', 'vertical'],
      description: 'The divider orientation.'
    },
    variant: {
      control: 'select',
      options: ['dashed', 'dotted', 'solid'],
      description: 'The line style variant.'
    },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.orientation !== undefined && args.orientation !== null) attrs.push(`orientation="${args.orientation}"`);
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  return `<ts-divider ${attrs.join(' ')}>
  </ts-divider>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "orientation": "horizontal",
      "variant": "solid"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-divider variant="dashed"></ts-divider>
    <ts-divider variant="dotted"></ts-divider>
    <ts-divider variant="solid"></ts-divider>
  </div>
`;

