// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Alert',
  tags: ['autodocs'],
  argTypes: {
    closable: { control: 'boolean', description: 'Whether the alert can be dismissed.' },
    variant: {
      control: 'select',
      options: ['danger', 'info', 'neutral', 'primary', 'secondary', 'success', 'warning'],
      description: 'The alert\'s semantic variant.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.closable) attrs.push('closable');
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  return `<ts-alert ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="action">${args['slot_action'] || ''}</span>
    <span slot="icon">${args['slot_icon'] || ''}</span>
  </ts-alert>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "closable": false,
      "variant": "info",
      "slotContent": "Content"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-alert variant="danger">Danger</ts-alert>
    <ts-alert variant="info">Info</ts-alert>
    <ts-alert variant="neutral">Neutral</ts-alert>
    <ts-alert variant="primary">Primary</ts-alert>
    <ts-alert variant="secondary">Secondary</ts-alert>
    <ts-alert variant="success">Success</ts-alert>
    <ts-alert variant="warning">Warning</ts-alert>
  </div>
`;

