// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Modal',
  tags: ['autodocs'],
  argTypes: {
    closeOnEscape: { control: 'boolean', description: 'Whether pressing Escape closes the modal.' },
    closeOnOverlay: { control: 'boolean', description: 'Whether clicking the overlay closes the modal.' },
    label: { control: 'text', description: 'Label for accessibility (used as aria-label).' },
    open: { control: 'boolean', description: 'Whether the modal is open.' },
    showClose: { control: 'boolean', description: 'Whether to show the close button.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The modal\'s width size preset.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.closeOnEscape) attrs.push('close-on-escape');
  if (args.closeOnOverlay) attrs.push('close-on-overlay');
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.open) attrs.push('open');
  if (args.showClose) attrs.push('show-close');
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  return `<ts-modal ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="footer">${args['slot_footer'] || ''}</span>
    <span slot="header">${args['slot_header'] || ''}</span>
  </ts-modal>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "closeOnEscape": true,
      "closeOnOverlay": true,
      "open": false,
      "showClose": true,
      "size": "md",
      "slotContent": "Content"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-modal size="lg">LG</ts-modal>
    <ts-modal size="md">MD</ts-modal>
    <ts-modal size="sm">SM</ts-modal>
    <ts-modal size="xl">XL</ts-modal>
    <ts-modal size="xs">XS</ts-modal>
  </div>
`;

