// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/SwitchOption',
  tags: ['autodocs'],
  argTypes: {
    active: { control: 'boolean', description: 'Whether this option is the active selection (set by parent).' },
    disabled: { control: 'boolean', description: 'Disables this option.' },
    icon: { control: 'text', description: 'Optional icon name.' },
    value: { control: 'text', description: 'Unique identifier for this option.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.active) attrs.push('active');
  if (args.disabled) attrs.push('disabled');
  if (args.icon !== undefined && args.icon !== null) attrs.push(`icon="${args.icon}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-switch-option ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-switch-option>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "active": false,
      "disabled": false,
      "slotContent": "Content"
  },
});

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-switch-option>Default</ts-switch-option>
    <ts-switch-option disabled>Disabled</ts-switch-option>
  </div>
`;

