// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/SwitchGroup',
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean', description: 'Disables the entire group.' },
    fullWidth: { control: 'boolean', description: 'Stretch to fill the container width.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The size of the switch group.'
    },
    value: { control: 'text', description: 'The currently active segment value.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.disabled) attrs.push('disabled');
  if (args.fullWidth) attrs.push('full-width');
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-switch-group ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-switch-group>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "fullWidth": false,
      "size": "md",
      "slotContent": "Content"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-switch-group size="lg">LG</ts-switch-group>
    <ts-switch-group size="md">MD</ts-switch-group>
    <ts-switch-group size="sm">SM</ts-switch-group>
    <ts-switch-group size="xl">XL</ts-switch-group>
    <ts-switch-group size="xs">XS</ts-switch-group>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-switch-group>Default</ts-switch-group>
    <ts-switch-group disabled>Disabled</ts-switch-group>
  </div>
`;

