// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Drawer',
  tags: ['autodocs'],
  argTypes: {
    dismissible: { control: 'boolean', description: 'Whether clicking the overlay or pressing Escape closes the drawer.' },
    heading: { control: 'text', description: 'Accessible heading for the drawer.' },
    open: { control: 'boolean', description: 'Whether the drawer is open.' },
    placement: {
      control: 'select',
      options: ['bottom', 'end', 'start', 'top'],
      description: 'Which edge the drawer slides in from.'
    },
    size: {
      control: 'select',
      options: ['full', 'lg', 'md', 'sm'],
      description: 'The drawer\'s width/height preset.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.dismissible) attrs.push('dismissible');
  if (args.heading !== undefined && args.heading !== null) attrs.push(`heading="${args.heading}"`);
  if (args.open) attrs.push('open');
  if (args.placement !== undefined && args.placement !== null) attrs.push(`placement="${args.placement}"`);
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  return `<ts-drawer ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="footer">${args['slot_footer'] || ''}</span>
  </ts-drawer>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "dismissible": true,
      "open": false,
      "placement": "end",
      "size": "md",
      "slotContent": "Content"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-drawer size="full">FULL</ts-drawer>
    <ts-drawer size="lg">LG</ts-drawer>
    <ts-drawer size="md">MD</ts-drawer>
    <ts-drawer size="sm">SM</ts-drawer>
  </div>
`;

