// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Checkbox',
  tags: ['autodocs'],
  argTypes: {
    checked: { control: 'boolean', description: 'Whether the checkbox is checked.' },
    disabled: { control: 'boolean', description: 'Renders the checkbox as disabled.' },
    error: { control: 'boolean', description: 'Renders the checkbox in an error state.' },
    indeterminate: { control: 'boolean', description: 'Whether the checkbox is in an indeterminate state.' },
    label: { control: 'text', description: 'Label text. If omitted, use the default slot.' },
    name: { control: 'text', description: 'Name attribute for form submission.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm'],
      description: 'The checkbox size.'
    },
    value: { control: 'text', description: 'The value associated with this checkbox.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.checked) attrs.push('checked');
  if (args.disabled) attrs.push('disabled');
  if (args.error) attrs.push('error');
  if (args.indeterminate) attrs.push('indeterminate');
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.name !== undefined && args.name !== null) attrs.push(`name="${args.name}"`);
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-checkbox ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-checkbox>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "checked": false,
      "disabled": false,
      "error": false,
      "indeterminate": false,
      "size": "md",
      "value": "",
      "slotContent": "Content"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-checkbox size="lg">LG</ts-checkbox>
    <ts-checkbox size="md">MD</ts-checkbox>
    <ts-checkbox size="sm">SM</ts-checkbox>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-checkbox>Default</ts-checkbox>
    <ts-checkbox checked>Checked</ts-checkbox>
    <ts-checkbox disabled>Disabled</ts-checkbox>
  </div>
`;

