// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Dialog',
  tags: ['autodocs'],
  argTypes: {
    dismissible: { control: 'boolean', description: 'Whether the dialog can be dismissed via close button, Escape, or overlay click.' },
    heading: { control: 'text', description: 'The dialog heading text.' },
    open: { control: 'boolean', description: 'Whether the dialog is open.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm'],
      description: 'The dialog\'s width size preset.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.dismissible) attrs.push('dismissible');
  if (args.heading !== undefined && args.heading !== null) attrs.push(`heading="${args.heading}"`);
  if (args.open) attrs.push('open');
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  return `<ts-dialog ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="footer">${args['slot_footer'] || ''}</span>
  </ts-dialog>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "dismissible": true,
      "open": false,
      "size": "sm",
      "slotContent": "Content"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-dialog size="lg">LG</ts-dialog>
    <ts-dialog size="md">MD</ts-dialog>
    <ts-dialog size="sm">SM</ts-dialog>
  </div>
`;

