// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/EmptyState',
  tags: ['autodocs'],
  argTypes: {
    description: { control: 'text', description: 'The description text.' },
    heading: { control: 'text', description: 'The heading text.' },
    icon: { control: 'text', description: 'Lucide icon name displayed large.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The size of the empty state.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.description !== undefined && args.description !== null) attrs.push(`description="${args.description}"`);
  if (args.heading !== undefined && args.heading !== null) attrs.push(`heading="${args.heading}"`);
  if (args.icon !== undefined && args.icon !== null) attrs.push(`icon="${args.icon}"`);
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  return `<ts-empty-state ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="action">${args['slot_action'] || ''}</span>
    <span slot="icon">${args['slot_icon'] || ''}</span>
  </ts-empty-state>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "size": "md",
      "slotContent": "Content"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-empty-state size="lg">LG</ts-empty-state>
    <ts-empty-state size="md">MD</ts-empty-state>
    <ts-empty-state size="sm">SM</ts-empty-state>
    <ts-empty-state size="xl">XL</ts-empty-state>
    <ts-empty-state size="xs">XS</ts-empty-state>
  </div>
`;

