// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Chip',
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean', description: 'Whether the chip is disabled.' },
    outline: { control: 'boolean', description: 'Whether to render as outline style.' },
    removable: { control: 'boolean', description: 'Whether the chip shows a remove button.' },
    selected: { control: 'boolean', description: 'Whether the chip is selected.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The chip\'s size.'
    },
    variant: {
      control: 'select',
      options: ['danger', 'info', 'neutral', 'primary', 'secondary', 'success', 'warning'],
      description: 'The chip\'s semantic variant.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.disabled) attrs.push('disabled');
  if (args.outline) attrs.push('outline');
  if (args.removable) attrs.push('removable');
  if (args.selected) attrs.push('selected');
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  return `<ts-chip ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="prefix">${args['slot_prefix'] || ''}</span>
  </ts-chip>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "outline": false,
      "removable": false,
      "selected": false,
      "size": "md",
      "variant": "neutral",
      "slotContent": "Content"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-chip variant="danger">Danger</ts-chip>
    <ts-chip variant="info">Info</ts-chip>
    <ts-chip variant="neutral">Neutral</ts-chip>
    <ts-chip variant="primary">Primary</ts-chip>
    <ts-chip variant="secondary">Secondary</ts-chip>
    <ts-chip variant="success">Success</ts-chip>
    <ts-chip variant="warning">Warning</ts-chip>
  </div>
`;

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-chip size="lg">LG</ts-chip>
    <ts-chip size="md">MD</ts-chip>
    <ts-chip size="sm">SM</ts-chip>
    <ts-chip size="xl">XL</ts-chip>
    <ts-chip size="xs">XS</ts-chip>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-chip>Default</ts-chip>
    <ts-chip disabled>Disabled</ts-chip>
  </div>
`;

