// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/DatePicker',
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean', description: 'Whether the date picker is disabled.' },
    error: { control: 'boolean', description: 'Whether the input is in an error state.' },
    errorMessage: { control: 'text', description: 'Error message to display.' },
    label: { control: 'text', description: 'Label text for the input.' },
    max: { control: 'text', description: 'Maximum selectable date in ISO format.' },
    min: { control: 'text', description: 'Minimum selectable date in ISO format.' },
    name: { control: 'text', description: 'Form field name.' },
    placeholder: { control: 'text', description: 'Placeholder text for the input.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm'],
      description: 'The input size.'
    },
    value: { control: 'text', description: 'The selected date value in ISO format (YYYY-MM-DD).' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.disabled) attrs.push('disabled');
  if (args.error) attrs.push('error');
  if (args.errorMessage !== undefined && args.errorMessage !== null) attrs.push(`error-message="${args.errorMessage}"`);
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.max !== undefined && args.max !== null) attrs.push(`max="${args.max}"`);
  if (args.min !== undefined && args.min !== null) attrs.push(`min="${args.min}"`);
  if (args.name !== undefined && args.name !== null) attrs.push(`name="${args.name}"`);
  if (args.placeholder !== undefined && args.placeholder !== null) attrs.push(`placeholder="${args.placeholder}"`);
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-date-picker ${attrs.join(' ')}>
  </ts-date-picker>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "error": false,
      "placeholder": "Select date",
      "size": "md"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-date-picker size="lg"></ts-date-picker>
    <ts-date-picker size="md"></ts-date-picker>
    <ts-date-picker size="sm"></ts-date-picker>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-date-picker></ts-date-picker>
    <ts-date-picker disabled></ts-date-picker>
  </div>
`;

