// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Table',
  tags: ['autodocs'],
  argTypes: {
    bordered: { control: 'boolean', description: 'Adds borders to all cells.' },
    compact: { control: 'boolean', description: 'Reduces cell padding for denser display.' },
    hoverable: { control: 'boolean', description: 'Highlights rows on hover.' },
    stickyHeader: { control: 'boolean', description: 'Makes the table header stick to the top on scroll.' },
    striped: { control: 'boolean', description: 'Applies alternating row background colors.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.bordered) attrs.push('bordered');
  if (args.compact) attrs.push('compact');
  if (args.hoverable) attrs.push('hoverable');
  if (args.stickyHeader) attrs.push('sticky-header');
  if (args.striped) attrs.push('striped');
  return `<ts-table ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-table>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "bordered": false,
      "compact": false,
      "hoverable": false,
      "stickyHeader": false,
      "striped": false,
      "slotContent": "Content"
  },
});

