// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Avatar',
  tags: ['autodocs'],
  argTypes: {
    alt: { control: 'text', description: 'Alt text for the avatar image.' },
    color: { control: 'text', description: 'Background color for the initials fallback.' },
    name: { control: 'text', description: 'Name used to generate initials fallback.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The size of the avatar.'
    },
    src: { control: 'text', description: 'Image URL for the avatar.' },
    variant: {
      control: 'select',
      options: ['circle', 'square'],
      description: 'Shape variant of the avatar.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.alt !== undefined && args.alt !== null) attrs.push(`alt="${args.alt}"`);
  if (args.color !== undefined && args.color !== null) attrs.push(`color="${args.color}"`);
  if (args.name !== undefined && args.name !== null) attrs.push(`name="${args.name}"`);
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.src !== undefined && args.src !== null) attrs.push(`src="${args.src}"`);
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  return `<ts-avatar ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-avatar>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "size": "md",
      "variant": "circle",
      "slotContent": "Content"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-avatar variant="circle">Circle</ts-avatar>
    <ts-avatar variant="square">Square</ts-avatar>
  </div>
`;

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-avatar size="lg">LG</ts-avatar>
    <ts-avatar size="md">MD</ts-avatar>
    <ts-avatar size="sm">SM</ts-avatar>
    <ts-avatar size="xl">XL</ts-avatar>
    <ts-avatar size="xs">XS</ts-avatar>
  </div>
`;

