// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Tooltip',
  tags: ['autodocs'],
  argTypes: {
    content: { control: 'text', description: 'The tooltip text content.' },
    disabled: { control: 'boolean', description: 'Disables the tooltip.' },
    hideDelay: { control: 'number', description: 'Delay in ms before hiding the tooltip.' },
    placement: {
      control: 'select',
      options: ['bottom', 'bottom-end', 'bottom-start', 'left', 'left-end', 'left-start', 'right', 'right-end', 'right-start', 'top', 'top-end', 'top-start'],
      description: 'Placement of the tooltip relative to the trigger.'
    },
    showDelay: { control: 'number', description: 'Delay in ms before showing the tooltip.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.content != null) attrs.push(`content="${args.content}"`);
  if (args.disabled) attrs.push('disabled');
  if (args.hideDelay != null) attrs.push(`hide-delay="${args.hideDelay}"`);
  if (args.placement != null) attrs.push(`placement="${args.placement}"`);
  if (args.showDelay != null) attrs.push(`show-delay="${args.showDelay}"`);
  return `<ts-tooltip ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-tooltip>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "content": "",
      "disabled": false,
      "hideDelay": 0,
      "placement": "top",
      "showDelay": 200,
      "slotContent": "Content"
  },
});

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-tooltip>Default</ts-tooltip>
    <ts-tooltip disabled>Disabled</ts-tooltip>
  </div>
`;

