// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Toggle',
  tags: ['autodocs'],
  argTypes: {
    checked: { control: 'boolean', description: 'Whether the toggle is checked.' },
    disabled: { control: 'boolean', description: 'Renders the toggle as disabled.' },
    name: { control: 'text', description: 'Name for form submission.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The toggle\'s size.'
    },
    value: { control: 'text', description: 'Value for form submission.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.checked) attrs.push('checked');
  if (args.disabled) attrs.push('disabled');
  if (args.name != null) attrs.push(`name="${args.name}"`);
  if (args.size != null) attrs.push(`size="${args.size}"`);
  if (args.value != null) attrs.push(`value="${args.value}"`);
  return `<ts-toggle ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-toggle>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "checked": false,
      "disabled": false,
      "size": "md",
      "slotContent": "Content"
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-toggle size="lg">LG</ts-toggle>
    <ts-toggle size="md">MD</ts-toggle>
    <ts-toggle size="sm">SM</ts-toggle>
    <ts-toggle size="xl">XL</ts-toggle>
    <ts-toggle size="xs">XS</ts-toggle>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-toggle>Default</ts-toggle>
    <ts-toggle checked>Checked</ts-toggle>
    <ts-toggle disabled>Disabled</ts-toggle>
  </div>
`;

