// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/NavItem',
  tags: ['autodocs'],
  argTypes: {
    active: { control: 'boolean', description: 'Whether this item is currently active.' },
    disabled: { control: 'boolean', description: 'Whether this item is disabled.' },
    href: { control: 'text', description: 'The URL to navigate to.' },
    icon: { control: 'text', description: 'Lucide icon name to display.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.active) attrs.push('active');
  if (args.disabled) attrs.push('disabled');
  if (args.href !== undefined && args.href !== null) attrs.push(`href="${args.href}"`);
  if (args.icon !== undefined && args.icon !== null) attrs.push(`icon="${args.icon}"`);
  return `<ts-nav-item ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-nav-item>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "active": false,
      "disabled": false,
      "slotContent": "Content"
  },
});

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-nav-item>Default</ts-nav-item>
    <ts-nav-item disabled>Disabled</ts-nav-item>
  </div>
`;

