// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Nav',
  tags: ['autodocs'],
  argTypes: {
    collapsed: { control: 'boolean', description: 'Whether the sidebar nav is collapsed (icons only).' },
    variant: {
      control: 'select',
      options: ['horizontal', 'sidebar'],
      description: 'The navigation layout variant.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.collapsed) attrs.push('collapsed');
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  return `<ts-nav ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-nav>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "collapsed": false,
      "variant": "sidebar",
      "slotContent": "Content"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-nav variant="horizontal">Horizontal</ts-nav>
    <ts-nav variant="sidebar">Sidebar</ts-nav>
  </div>
`;

