// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/AccordionItem',
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean', description: 'Disables toggling.' },
    heading: { control: 'text', description: 'Header text for the item.' },
    open: { control: 'boolean', description: 'Whether the item is expanded.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.disabled) attrs.push('disabled');
  if (args.heading !== undefined && args.heading !== null) attrs.push(`heading="${args.heading}"`);
  if (args.open) attrs.push('open');
  return `<ts-accordion-item ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="header">${args['slot_header'] || ''}</span>
  </ts-accordion-item>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "open": false,
      "slotContent": "Content"
  },
});

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-accordion-item>Default</ts-accordion-item>
    <ts-accordion-item disabled>Disabled</ts-accordion-item>
  </div>
`;

