// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Accordion',
  tags: ['autodocs'],
  argTypes: {
    multiple: { control: 'boolean', description: 'Allow multiple items to be open simultaneously.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.multiple) attrs.push('multiple');
  return `<ts-accordion ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-accordion>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "multiple": false,
      "slotContent": "Content"
  },
});

