// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Tree',
  tags: ['autodocs'],
  argTypes: {
    selectable: { control: 'boolean', description: 'Enable item selection mode.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.selectable) attrs.push('selectable');
  return `<ts-tree ${attrs.join(' ')}>${args.slotContent || ''}
  </ts-tree>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "selectable": false,
      "slotContent": "Content"
  },
});

