// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/TreeItem',
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean', description: 'Whether the item is disabled.' },
    expanded: { control: 'boolean', description: 'Whether the item is expanded (has children).' },
    icon: { control: 'text', description: 'Optional Lucide icon name.' },
    label: { control: 'text', description: 'The item label.' },
    selected: { control: 'boolean', description: 'Whether the item is selected.' },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.disabled) attrs.push('disabled');
  if (args.expanded) attrs.push('expanded');
  if (args.icon !== undefined && args.icon !== null) attrs.push(`icon="${args.icon}"`);
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.selected) attrs.push('selected');
  return `<ts-tree-item ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="label">${args['slot_label'] || ''}</span>
  </ts-tree-item>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "expanded": false,
      "selected": false,
      "slotContent": "Content"
  },
});

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-tree-item>Default</ts-tree-item>
    <ts-tree-item disabled>Disabled</ts-tree-item>
  </div>
`;

