// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Banner',
  tags: ['autodocs'],
  argTypes: {
    dismissible: { control: 'boolean', description: 'Whether the banner can be dismissed.' },
    icon: { control: 'text', description: 'Optional Lucide icon name.' },
    sticky: { control: 'boolean', description: 'Whether the banner sticks to the top of the viewport.' },
    variant: {
      control: 'select',
      options: ['danger', 'info', 'neutral', 'primary', 'secondary', 'success', 'warning'],
      description: 'The banner\'s semantic variant.'
    },
    slotContent: { control: 'text', description: 'Default slot content' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.dismissible) attrs.push('dismissible');
  if (args.icon !== undefined && args.icon !== null) attrs.push(`icon="${args.icon}"`);
  if (args.sticky) attrs.push('sticky');
  if (args.variant !== undefined && args.variant !== null) attrs.push(`variant="${args.variant}"`);
  return `<ts-banner ${attrs.join(' ')}>${args.slotContent || ''}
    <span slot="action">${args['slot_action'] || ''}</span>
  </ts-banner>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "dismissible": false,
      "sticky": false,
      "variant": "info",
      "slotContent": "Content"
  },
});

export const Variants = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-banner variant="danger">Danger</ts-banner>
    <ts-banner variant="info">Info</ts-banner>
    <ts-banner variant="neutral">Neutral</ts-banner>
    <ts-banner variant="primary">Primary</ts-banner>
    <ts-banner variant="secondary">Secondary</ts-banner>
    <ts-banner variant="success">Success</ts-banner>
    <ts-banner variant="warning">Warning</ts-banner>
  </div>
`;

