// @auto-generated by storybook-output-target — edits will be overwritten on next build

export default {
  title: 'Components/Slider',
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean', description: 'Disables the slider.' },
    label: { control: 'text', description: 'Accessible label.' },
    max: { control: 'number', description: 'Maximum value.' },
    min: { control: 'number', description: 'Minimum value.' },
    showValue: { control: 'boolean', description: 'Whether to display the current value.' },
    size: {
      control: 'select',
      options: ['lg', 'md', 'sm', 'xl', 'xs'],
      description: 'The size of the slider.'
    },
    step: { control: 'number', description: 'Step increment.' },
    value: { control: 'number', description: 'Current slider value.' },
  },
};

const Template = (args: Record<string, unknown>) => {
  const attrs: string[] = [];
  if (args.disabled) attrs.push('disabled');
  if (args.label !== undefined && args.label !== null) attrs.push(`label="${args.label}"`);
  if (args.max !== undefined && args.max !== null) attrs.push(`max="${args.max}"`);
  if (args.min !== undefined && args.min !== null) attrs.push(`min="${args.min}"`);
  if (args.showValue) attrs.push('show-value');
  if (args.size !== undefined && args.size !== null) attrs.push(`size="${args.size}"`);
  if (args.step !== undefined && args.step !== null) attrs.push(`step="${args.step}"`);
  if (args.value !== undefined && args.value !== null) attrs.push(`value="${args.value}"`);
  return `<ts-slider ${attrs.join(' ')}>
  </ts-slider>`;
};

export const Default = Object.assign(Template.bind({}) as typeof Template & { args: Record<string, unknown> }, {
  args: {
      "disabled": false,
      "max": 100,
      "min": 0,
      "showValue": false,
      "size": "md",
      "step": 1,
      "value": 0
  },
});

export const Sizes = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-slider size="lg"></ts-slider>
    <ts-slider size="md"></ts-slider>
    <ts-slider size="sm"></ts-slider>
    <ts-slider size="xl"></ts-slider>
    <ts-slider size="xs"></ts-slider>
  </div>
`;

export const States = () => `
  <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center;">
    <ts-slider></ts-slider>
    <ts-slider disabled></ts-slider>
  </div>
`;

